/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package RfortuneTeam.HeatherandLaura.frames;

/**
 *
 * @author Heather
 */
public class EndingScreen extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public EndingScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfWinnerMessage = new javax.swing.JTextField();
        jtfWinnerName = new javax.swing.JTextField();
        jtfPlayer1Name = new javax.swing.JTextField();
        jtfPlayer2Name = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jtfPlayer1Bank = new javax.swing.JTextField();
        jbNewGame = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();
        jtfPlayer1Bank1 = new javax.swing.JTextField();
        jtfPlayer1Bank2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 5));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RECTANGLE OF FORTUNE");

        jtfWinnerMessage.setEditable(false);
        jtfWinnerMessage.setBackground(new java.awt.Color(0, 102, 102));
        jtfWinnerMessage.setFont(new java.awt.Font("Lucida Sans", 0, 48)); // NOI18N
        jtfWinnerMessage.setForeground(new java.awt.Color(0, 153, 153));
        jtfWinnerMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfWinnerMessage.setText("Congratulations ");
        jtfWinnerMessage.setBorder(null);

        jtfWinnerName.setEditable(false);
        jtfWinnerName.setBackground(new java.awt.Color(0, 102, 102));
        jtfWinnerName.setFont(new java.awt.Font("Lucida Sans", 0, 30)); // NOI18N
        jtfWinnerName.setForeground(new java.awt.Color(0, 153, 153));
        jtfWinnerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfWinnerName.setText("PlayerName");
        jtfWinnerName.setBorder(null);

        jtfPlayer1Name.setEditable(false);
        jtfPlayer1Name.setBackground(new java.awt.Color(0, 102, 102));
        jtfPlayer1Name.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jtfPlayer1Name.setForeground(new java.awt.Color(153, 153, 153));
        jtfPlayer1Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfPlayer1Name.setText("Player One");

        jtfPlayer2Name.setEditable(false);
        jtfPlayer2Name.setBackground(new java.awt.Color(0, 102, 102));
        jtfPlayer2Name.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jtfPlayer2Name.setForeground(new java.awt.Color(153, 153, 153));
        jtfPlayer2Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfPlayer2Name.setText("Player Two");

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(0, 102, 102));
        jTextField5.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Player Three");

        jtfPlayer1Bank.setEditable(false);
        jtfPlayer1Bank.setBackground(new java.awt.Color(0, 102, 102));
        jtfPlayer1Bank.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jtfPlayer1Bank.setForeground(new java.awt.Color(153, 153, 153));
        jtfPlayer1Bank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfPlayer1Bank.setText("Bank");

        jbNewGame.setBackground(new java.awt.Color(153, 153, 153));
        jbNewGame.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jbNewGame.setText("New Game");
        jbNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewGameActionPerformed(evt);
            }
        });

        jbExit.setBackground(new java.awt.Color(153, 153, 153));
        jbExit.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jbExit.setText("Exit");

        jtfPlayer1Bank1.setEditable(false);
        jtfPlayer1Bank1.setBackground(new java.awt.Color(0, 102, 102));
        jtfPlayer1Bank1.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jtfPlayer1Bank1.setForeground(new java.awt.Color(153, 153, 153));
        jtfPlayer1Bank1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfPlayer1Bank1.setText("Bank");

        jtfPlayer1Bank2.setEditable(false);
        jtfPlayer1Bank2.setBackground(new java.awt.Color(0, 102, 102));
        jtfPlayer1Bank2.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jtfPlayer1Bank2.setForeground(new java.awt.Color(153, 153, 153));
        jtfPlayer1Bank2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfPlayer1Bank2.setText("Bank");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfWinnerName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfWinnerMessage, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfPlayer1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfPlayer1Bank, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(118, 118, 118)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfPlayer2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfPlayer1Bank1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtfPlayer1Bank2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jbNewGame)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jbExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfWinnerMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtfWinnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPlayer1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPlayer2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPlayer1Bank, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPlayer1Bank1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPlayer1Bank2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jbNewGame)
                .addGap(18, 18, 18)
                .addComponent(jbExit)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbNewGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JButton jbExit;
    public javax.swing.JButton jbNewGame;
    public javax.swing.JTextField jtfPlayer1Bank;
    public javax.swing.JTextField jtfPlayer1Bank1;
    public javax.swing.JTextField jtfPlayer1Bank2;
    public javax.swing.JTextField jtfPlayer1Name;
    public javax.swing.JTextField jtfPlayer2Name;
    public javax.swing.JTextField jtfWinnerMessage;
    public javax.swing.JTextField jtfWinnerName;
    // End of variables declaration//GEN-END:variables
}
