/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RfortuneTeam.HeatherandLaura.frames;

import RfortuneTeam.HeatherandLaura.control.MainMenuControl;
import rfortune.Game;
import rfortune.Player;
import rfortune.PlayerTurn;
import rfortune.PlayersList;
import rfortune.Rfortune;
import rfortune.RfortuneError;
import rfortune.WordsAndPhrases;

/**
 *
 * @author Laura
 */
public class EnterPlayerNames extends javax.swing.JFrame {

    MainMenuControl mainMenuControl = new MainMenuControl();
    PlayersList playersList = new PlayersList();
    PlayerTurn playerTurn = new PlayerTurn();
    WordsAndPhrases wordsAndPhrases = new WordsAndPhrases();
    Game game = new Game();
    public static int control = 0;

    /**
     * Creates new form EnterPlayerNames
     */
    public EnterPlayerNames() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcb1PlayerG = new javax.swing.JCheckBox();
        jcb2PlayerG = new javax.swing.JCheckBox();
        jcb3PlayerG = new javax.swing.JCheckBox();
        jtfPlayer1 = new javax.swing.JTextField();
        jtfPlayer2 = new javax.swing.JTextField();
        jtfPlayer3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbContinuePlayerNames = new javax.swing.JButton();
        jbBack = new javax.swing.JButton();
        jbValidate1 = new javax.swing.JButton();
        jbValidate2 = new javax.swing.JButton();
        jbValidate3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enter Player Names");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Player Names");

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel2.setText("First select appropriate box:");

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel3.setText("Then validate each name before clicking Continue ");

        jcb1PlayerG.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jcb1PlayerG);
        jcb1PlayerG.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jcb1PlayerG.setText("1 Player Game");
        jcb1PlayerG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb1PlayerGActionPerformed(evt);
            }
        });

        jcb2PlayerG.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jcb2PlayerG);
        jcb2PlayerG.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jcb2PlayerG.setText("2 Player Game");
        jcb2PlayerG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb2PlayerGActionPerformed(evt);
            }
        });

        jcb3PlayerG.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jcb3PlayerG);
        jcb3PlayerG.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jcb3PlayerG.setText("3 Player Game");
        jcb3PlayerG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb3PlayerGActionPerformed(evt);
            }
        });

        jtfPlayer1.setEditable(false);

        jtfPlayer2.setEditable(false);

        jtfPlayer3.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel4.setText("Players Name");

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel5.setText("Players Name");

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel6.setText("Players Name");

        jbContinuePlayerNames.setBackground(new java.awt.Color(153, 153, 153));
        jbContinuePlayerNames.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbContinuePlayerNames.setText("Continue");
        jbContinuePlayerNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbContinuePlayerNamesActionPerformed(evt);
            }
        });

        jbBack.setBackground(new java.awt.Color(153, 153, 153));
        jbBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbBack.setText("Back");
        jbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBackActionPerformed(evt);
            }
        });

        jbValidate1.setBackground(new java.awt.Color(153, 153, 153));
        jbValidate1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbValidate1.setText("Submit");
        jbValidate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbValidate1ActionPerformed(evt);
            }
        });

        jbValidate2.setBackground(new java.awt.Color(153, 153, 153));
        jbValidate2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbValidate2.setText("Submit");
        jbValidate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbValidate2ActionPerformed(evt);
            }
        });

        jbValidate3.setBackground(new java.awt.Color(153, 153, 153));
        jbValidate3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbValidate3.setText("Submit");
        jbValidate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbValidate3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jcb1PlayerG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jcb3PlayerG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jcb2PlayerG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jbValidate1)
                                                .addGap(31, 31, 31))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jbValidate2)
                                                    .addComponent(jbValidate3))
                                                .addContainerGap())))
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbContinuePlayerNames, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb1PlayerG)
                    .addComponent(jtfPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jbValidate1))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb2PlayerG)
                    .addComponent(jtfPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jbValidate2))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcb3PlayerG)
                        .addComponent(jtfPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbValidate3))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBack)
                    .addComponent(jbContinuePlayerNames))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbValidate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbValidate3ActionPerformed
        String player3 = jtfPlayer3.getText().trim();
        playersList.checkInput(player3);
        if (PlayersList.getJustRight()) {
            Player.setPlayer3(player3);
            control++;
            jtfPlayer3.setEditable(false);
        }
    }//GEN-LAST:event_jbValidate3ActionPerformed

    private void jbValidate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbValidate2ActionPerformed
        String player2 = jtfPlayer2.getText().trim();
        playersList.checkInput(player2);
        if (PlayersList.getJustRight()) {
            Player.setPlayer2(player2);
            control++;
            jtfPlayer2.setEditable(false);
        }
    }//GEN-LAST:event_jbValidate2ActionPerformed

    private void jbValidate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbValidate1ActionPerformed
        String player1 = jtfPlayer1.getText().trim();
        playersList.checkInput(player1);
        if (PlayersList.getJustRight()) {
            Player.setPlayer1(player1);
            control++;
            jtfPlayer1.setEditable(false);
        }
    }//GEN-LAST:event_jbValidate1ActionPerformed

    private void jbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBackActionPerformed
        new Rfortune().newGame();
        this.dispose();
    }//GEN-LAST:event_jbBackActionPerformed

    private void jbContinuePlayerNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbContinuePlayerNamesActionPerformed
        boolean ready = false;
        if (MainMenuControl.getSetNumPlayers() == 1) {
            if (control == 1) {
                ready = true;
            }
            if (Player.getPlayer1().isEmpty()) {
                new RfortuneError().displayError("Player One needs a name");
            }

        }
        if (MainMenuControl.getSetNumPlayers() == 2) {
            if (control == 2) {
                ready = true;
            }
            if (control == 1) {
                if (Player.getPlayer1().isEmpty()) {
                    new RfortuneError().displayError("Player One needs a name");
                }
                if (Player.getPlayer2().isEmpty()) {
                    new RfortuneError().displayError("Player Two needs a name");
                }
            }
            if (control == 0) {
                new RfortuneError().displayError("Enter names first");
            }

        }
        if (MainMenuControl.getSetNumPlayers() == 3) {
            if (control == 3) {
                ready = true;
            }
            if (control == 1 || control == 2) {
                if (Player.getPlayer1().isEmpty()) {
                    new RfortuneError().displayError("Player One needs a name");
                }
                if (Player.getPlayer2().isEmpty()) {
                    new RfortuneError().displayError("Player Two needs a name");
                }
                if (Player.getPlayer3().isEmpty()) {
                    new RfortuneError().displayError("Player Three needs a name");
                }
            }
            if (control == 0) {
                new RfortuneError().displayError("Enter names first");
            }

        }
        if (MainMenuControl.getSetNumPlayers() == 0) {
            new RfortuneError().displayError("How many people are playing? Check the box.");
        }
        if (ready) {
            playersList.resetList();
            game.startGame();
            mainMenuControl.startGameMenu();
            this.dispose();
        }
    }//GEN-LAST:event_jbContinuePlayerNamesActionPerformed

    private void jcb3PlayerGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb3PlayerGActionPerformed
        mainMenuControl.setNumPlayers(3);
        if (MainMenuControl.getSetNumPlayers() == 3) {
            jtfPlayer1.setEditable(rootPaneCheckingEnabled);
            jtfPlayer2.setEditable(rootPaneCheckingEnabled);
            jtfPlayer3.setEditable(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_jcb3PlayerGActionPerformed

    private void jcb2PlayerGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb2PlayerGActionPerformed
        mainMenuControl.setNumPlayers(2);
        if (MainMenuControl.getSetNumPlayers() == 2) {
            jtfPlayer1.setEditable(rootPaneCheckingEnabled);
            jtfPlayer2.setEditable(rootPaneCheckingEnabled);
            jtfPlayer3.setEditable(false);
        }
    }//GEN-LAST:event_jcb2PlayerGActionPerformed

    private void jcb1PlayerGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb1PlayerGActionPerformed
        mainMenuControl.setNumPlayers(1);
        if (MainMenuControl.getSetNumPlayers() == 1) {
            jtfPlayer1.setEditable(rootPaneCheckingEnabled);
            jtfPlayer2.setEditable(false);
            jtfPlayer3.setEditable(false);
        }
    }//GEN-LAST:event_jcb1PlayerGActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbBack;
    private javax.swing.JButton jbContinuePlayerNames;
    private javax.swing.JButton jbValidate1;
    private javax.swing.JButton jbValidate2;
    private javax.swing.JButton jbValidate3;
    public javax.swing.JCheckBox jcb1PlayerG;
    public javax.swing.JCheckBox jcb2PlayerG;
    public javax.swing.JCheckBox jcb3PlayerG;
    public javax.swing.JTextField jtfPlayer1;
    public javax.swing.JTextField jtfPlayer2;
    public javax.swing.JTextField jtfPlayer3;
    // End of variables declaration//GEN-END:variables
}
