/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package RfortuneTeam.HeatherandLaura.frames;

import RfortuneTeam.HeatherandLaura.control.GamePreferencesControl;

/**
 *
 * @author Heather
 */
public class GamePrefs extends javax.swing.JFrame {
    
    GamePreferencesControl gamePrefsControl = new GamePreferencesControl();

    /**
     * Creates new form GamePrefs
     */
    public GamePrefs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrbEasyMode = new javax.swing.JRadioButton();
        jrbHardMode = new javax.swing.JRadioButton();
        jbSubmitPrefs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Game Preferences");

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel2.setText("Select Game Mode: ");

        jrbEasyMode.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbEasyMode);
        jrbEasyMode.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jrbEasyMode.setSelected(true);
        jrbEasyMode.setText("Easy");
        jrbEasyMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEasyModeActionPerformed(evt);
            }
        });

        jrbHardMode.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(jrbHardMode);
        jrbHardMode.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jrbHardMode.setText("Hard");
        jrbHardMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbHardModeActionPerformed(evt);
            }
        });

        jbSubmitPrefs.setBackground(new java.awt.Color(153, 153, 153));
        jbSubmitPrefs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbSubmitPrefs.setText("Submit");
        jbSubmitPrefs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubmitPrefsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbHardMode)
                            .addComponent(jrbEasyMode))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jbSubmitPrefs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbEasyMode)
                .addGap(18, 18, 18)
                .addComponent(jrbHardMode)
                .addGap(18, 18, 18)
                .addComponent(jbSubmitPrefs)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSubmitPrefsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubmitPrefsActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSubmitPrefsActionPerformed

    private void jrbEasyModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEasyModeActionPerformed
        gamePrefsControl.setDifficulty(1);
    }//GEN-LAST:event_jrbEasyModeActionPerformed

    private void jrbHardModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbHardModeActionPerformed
        gamePrefsControl.setDifficulty(2);
    }//GEN-LAST:event_jrbHardModeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbSubmitPrefs;
    public javax.swing.JRadioButton jrbEasyMode;
    public javax.swing.JRadioButton jrbHardMode;
    // End of variables declaration//GEN-END:variables
}
